name: release

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:
  release:
    types: [published]

jobs:
  upload-artifacts:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: linux
            os: { name: linux-x86-64, version: ubuntu-24.04 }
            label: linux-x86_64

          - host: linux
            os: { name: linux-arm64, version: ubuntu-24.04-arm }
            label: linux-aarch64

          - host: windows
            os: { name: windows, version: windows-latest }
            label: windows-x86_64

          - host: macos
            os: { name: macos, version: macos-latest }
            label: macos-x86_64

    name: build
    runs-on: ${{ matrix.os.version }}
    env:
      BINARY: aya_${{ matrix.label }}
      ARCHIVE: aya_${{ matrix.label }}.${{ matrix.host == 'windows' && 'zip' || 'tar.gz' }}
    steps:
      - uses: actions/checkout@v4

      - name: setup rokit
        uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab

      - name: compile
        run: lute compile-release-artifact

      - name: upload
        env:
          GITHUB_TOKEN: ${{ secrets.AYA_RELEASE_PAT }}
        run: gh release upload "${{ github.event.release.tag_name }}" "release/$ARCHIVE" --clobber
